### PR TITLE
Update projector_notes.md

### PR DESCRIPTION
**Pull request by tornel**
Feel free to correct any misspellings or syntax errors, I'm not a native English speaker.

### CODE REVIEW

**Comment by stuffmatic** [comment]
Thanks for this! 

About the [Blender bug](https://developer.blender.org/T70800) you mentioned, it only affects Cycles, right? (and not Eevee)

**Comment by tornel** [comment]
Correct, the bug only affects Cycles

**Comment by stuffmatic** [comment]
Do you have reliable steps to reproduce the issue? Could maybe be a good idea to add a comment on the issue in the Blender issue tracker. Looks like they are stuck waiting for more input.

**Comment by tornel** [comment]
Just the same that are already in the bug report:

1. Open blender
2. Ser render to Cycles
3. Activate Render view 
4. Toggle  Full Screen
5. Toggle Maximize Area (ctrl-alt-space)

I have only tested in Windows 10 with an Nvidia Card,

**Pull request merged**
